# Generated by Django 5.1.5 on 2025-04-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_cart_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
